project:
  type: website
  output-dir: docs

website:
  title: "OS course"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - course_content.qmd
      - courses.qmd
      - about_us.qmd

  page-footer:
    left: "This page is built with ❤️🧠 and [Quarto](https://quarto.org/)."
    right:
    - text: "License"
      #href: LICENSE.md

format:
  html:
    theme:
      light: [cosmo, style/dsbox.scss]
      # dark: [cosmo, style/dsbox.scss, style/dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    # mainfont: "Atkinson Hyperlegible"
    # include-in-header: "style/fontawesome.html"

editor: visual
